version: '3.8'

services:
  # Redis - 3 인스턴스
  mlb-redis1:
    image: redis:7.2
    container_name: mlb-redis1
    ports:
      - "6379:6379"
    networks:
      - backend

  mlb-redis2:
    image: redis:7.2
    container_name: mlb-redis2
    ports:
      - "6380:6379"
    networks:
      - backend

  mlb-redis3:
    image: redis:7.2
    container_name: mlb-redis3
    ports:
      - "6381:6379"
    networks:
      - backend

  # Elasticsearch
  mlb-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: mlb-elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - backend

  # Zookeeper (for Kafka)
  mlb-zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: mlb-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend

  # Kafka
  mlb-kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: mlb-kafka
    depends_on:
      - mlb-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: mlb-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

volumes:
  es_data:

networks:
  backend:
    driver: bridge



