version: '3.8'

services:
  # Redis - 3 인스턴스
  mlb-redis1:
    image: redis:7.2
    container_name: mlb-redis1
    ports:
      - "6379:6379"
    networks:
      - backend

  mlb-redis2:
    image: redis:7.2
    container_name: mlb-redis2
    ports:
      - "6380:6379"
    networks:
      - backend

  mlb-redis3:
    image: redis:7.2
    container_name: mlb-redis3
    ports:
      - "6381:6379"
    networks:
      - backend

    # Elasticsearch (8.x, 보안 off)
  mlb-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: mlb-elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g   # 로컬 자원에 맞춰 조절
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks: [backend]

volumes:
  redis_data:
  es_data:

networks:
  backend:
    driver: bridge


