name: Deploy to Amazon Linux EC2 (compose-prod)

on:
  push:
    branches: [ main ]   # main 브랜치 푸시 시 배포
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2) EC2로 소스/설정 전송 (JAR 빌드 불필요)
      - name: Upload project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            backendProject/**
            docker-compose-prod.yml
            .env
          target: ${{ secrets.EC2_APP_DIR }}

      # 3) EC2에서 배포 실행
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            APP_DIR="${{ secrets.EC2_APP_DIR }}"
            cd "$APP_DIR"

            # Docker/compose 설치 (없으면)
            if ! command -v docker >/dev/null 2>&1; then
              if command -v dnf >/dev/null 2>&1; then
                sudo dnf -y update
                sudo dnf -y install docker
              else
                sudo yum -y update
                sudo yum -y install docker
              fi
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker ec2-user || true
            fi
            if ! docker compose version >/dev/null 2>&1; then
              if command -v dnf >/dev/null 2>&1; then
                sudo dnf -y install docker-compose-plugin
              else
                sudo yum -y install docker-compose-plugin || true
              fi
            fi

            # 기존 컨테이너 중지 후 재빌드/재기동
            sudo docker compose -f docker-compose-prod.yml down || true
            sudo docker compose -f docker-compose-prod.yml build --no-cache
            sudo docker compose -f docker-compose-prod.yml up -d

            # (옵션) 안 쓰는 이미지 정리
            sudo docker image prune -f

      # 4) (선택) CloudFront 캐시 무효화
      - name: Set CloudFront ID as env var
        run: echo "CF_ID=${{ secrets.CF_DISTRIBUTION_ID }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        if: env.CF_ID != ''
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront
        if: env.CF_ID != ''
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ env.CF_ID }}" \
            --paths "/*"
